all:
	@echo "use \"make copy\" to copy the files to your user's Inkscape directory."

copy:  
	/bin/cp ./*.py ~/.config/inkscape/extensions
	/bin/cp ./*.inx ~/.config/inkscape/extensions
	/bin/cp ../printarea/uArmSwiftPro_Max.svg ~/.config/inkscape/extensions
